version: '3.1'
services:

    api:
      build: ./
      ports:
        - "8080:8080"
      depends_on:
        - postgres

    postgres:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: workers_db
      ports:
        - "5432:5432"
